services:
  - type: web
    name: prime-mart
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommerce.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://primemartdb_user:kd6pDV7muquhynI1bLMnaelQqZT9KMSL@dpg-d02v9m3uibrs73b96qrg-a/primemartdb
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.production_settings
      - key: DEBUG
        value: "False"
    plan: free
